server.port=9095
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kumarsuraj.p22@gmail.com
spring.mail.password=ofdq oyis mzut hcgq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

#give access to less secure apps in gmail account,
#now, to send mail we have to go to gmail >> turn-on the two factor authnetication by going inside security section
#>> manage account >> home >> serach for "app password"
#>> select other app >> generate password