spring.application.name=SpringAiWithOpenAi
server.port=8096
spring.ai.openai.api-key=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